### ISSUE TITLE
how to pass the data through .property file or .csv 

### ISSUE THREAD

**Issue by ChethanGKC** [phystem/AwsDeviceFarmTest#1]
@phystem : Can you please let me know how can i pass the test data through files (like .property, .csv, etc..,.) in AWS DeviceForm.

For eg. I need to pass the test data like user name and password through any of  the files.

Thanks in advance.

**Comment by phystem** [comment]
@ChethanGKC  aws device farm just needs a zip file of the project. you can write code in your project however you want.  and stackoverflow is the best platform for these kind of questions.

**Comment by ChethanGKC** [comment]
@phystem - Thanks for the replay, yes I resolved this issue by combining the test data file inside the test jar file. Thanks again :)
